local cmd = vim.api.nvim_create_user_command
cmd("FzfKastenDaily", function() require('fzfkasten').goto_daily() end, { desc = "Fzfkasten: Daily Note" })
cmd("FzfKastenWeekly", function() require('fzfkasten').goto_weekly() end, { desc = "Fzfkasten: Weekly Note" })
cmd("FzfKastenFindNotes", function() require('fzfkasten').find_notes() end, { desc = "Fzfkasten: Find notes" })
cmd("FzfKastenTags", function() require('fzfkasten').search_tags() end, { desc = "Fzfkasten: Search Tags (all occurrences)" })
cmd("FzfKastenSearchByTag", function() require('fzfkasten').search_by_tag() end, { desc = "Fzfkasten: Filter notes by tag" })
cmd("FzfKastenInsert", function() require('fzfkasten').insert_link() end, { desc = "Fzfkasten: Insert Link" })
cmd("FzfKastenSearchContent", function() require('fzfkasten').search_content() end, { desc = "Fzfkasten: Search note content" })
cmd("FzfKastenNewNote", function() require('fzfkasten').new_note() end, { desc = "Fzfkasten: Create a new note" })
cmd("FzfKastenRenameNote", function() require('fzfkasten').rename_note() end, { desc = "Fzfkasten: Rename current note and update links" })
cmd("FzfKastenPanel", function() require('fzfkasten').panel() end, { desc = "Fzfkasten: Panel" })
cmd("FzfKastenFollowLink", function() require('fzfkasten').follow_link() end, { desc = "Fzfkasten: Follow Link" })
cmd("FzfKastenGotoLink", function() require('fzfkasten').goto_link() end, { desc = "Fzfkasten: Follow link under cursor (gf-style, falls back to native gf)" })
cmd("FzfKastenShowBacklinks", function() require('fzfkasten').show_backlinks() end, { desc = "Fzfkasten: Show Backlinks" })
cmd("FzfKastenFindDailyNotes", function() require('fzfkasten').find_daily_notes() end, { desc = "Fzfkasten: Find Daily Notes" })
cmd("FzfKastenLog", function() require('fzfkasten').log() end, { desc = "Fzfkasten: Browse or create daily/weekly notes by date, with preview" })
cmd("FzfKastenPickDailyDate", function() require('fzfkasten').log() end, { desc = "Fzfkasten: Alias of FzfKastenLog (kept for compatibility)" })
cmd("FzfKastenFindWeeklyNotes", function() require('fzfkasten').find_weekly_notes() end, { desc = "Fzfkasten: Find Weekly Notes" })
cmd("FzfKastenTasks", function() require('fzfkasten').tasks() end, { desc = "Fzfkasten: Pick an open task and jump to its note" })
cmd("FzfKastenTaskToggle", function() require('fzfkasten').task_toggle() end, { desc = "Fzfkasten: Toggle the checkbox on the current line" })
cmd("FzfKastenTaskInbox", function() require('fzfkasten').task_inbox() end, { desc = "Fzfkasten: Triage checkboxes that aren't tagged as tasks" })
cmd("FzfKastenTaskAdd", function(o) require('fzfkasten').task_add(o.args) end, { nargs = "?", desc = "Fzfkasten: Capture a new task to the capture note (prompts with no argument)" })
cmd("FzfKastenTaskTag", function(o) require('fzfkasten').task_tag({ line1 = o.line1, line2 = o.line2 }) end, { range = true, desc = "Fzfkasten: Tag the current line (or range) as a task" })
cmd("FzfKastenTaskCancel", function() require('fzfkasten').task_cancel() end, { desc = "Fzfkasten: Cancel the task on the current line, or reopen it" })
cmd("FzfKastenTaskDue", function(o) require('fzfkasten').task_due(o.args) end, { nargs = "?", desc = "Fzfkasten: Set (or, with no argument, clear) the due date on the current task" })
cmd("FzfKastenTaskUndo", function() require('fzfkasten').task_undo() end, { desc = "Fzfkasten: Put back the last task line the picker rewrote" })
cmd("FzfKastenTaskList", function() require('fzfkasten').task_list() end, { desc = "Fzfkasten: Task list as a buffer, worked with Vim keys" })
cmd("FzfKastenTaskListInbox", function() require('fzfkasten').task_list_inbox() end, { desc = "Fzfkasten: Task list buffer, showing the inbox" })
cmd("FzfKastenClaudeSendBuffer", function() require('fzfkasten').claude_send_buffer() end, { desc = "Fzfkasten: Send note to Claude" })
cmd("FzfKastenClaudeSendSelection", function() require('fzfkasten').claude_send_selection() end, { range = true, desc = "Fzfkasten: Send selection to Claude" })
cmd("FzfKastenClaudeToggle", function() require('fzfkasten').claude_toggle() end, { desc = "Fzfkasten: Toggle Claude terminal" })